---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luisgar2/public_html/sueldos.btzminera.com.ar
    - /bin/cp -R server.js database.js package.json package-lock.json $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
